resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
  ---
  test:
    hosts:
      wireguard:
        ansible_host: ${resource.yandex_compute_instance.vm-1.network_interface.0.nat_ip_address}
        ansible_user: ubuntu	
    DOC
  filename = "ansible/inventory/prod.yml"

  depends_on = [
    yandex_compute_instance.vm-1,
  ]
}
